[dump] Add ACL modules
sonic-net/SONiC pull request #983
Opened 2022-04-15 12:17 UTC by stepanblyschak

Signed-off-by: Stepan Blyschak <stepanb@nvidia.com>

2022-04-25 09:04 UTC, liat-grozovik commented
@vivekreddynv could you please help to review?

2022-04-25 18:02 UTC, vivekreddynv requested changes

2022-04-25 18:02 UTC, vivekreddynv commented on doc/Dump-Utility.md
> +ACL Tables configuration resieds in CONFIG DB in table *ACL_TABLE*. Tables in *ACL_TABLE* may reference another table *ACL_TABLE_TYPE* that holds the table type configuration or may use one of defaul
typo "resides"

2022-04-26 10:17 UTC, stepanblyschak commented on doc/Dump-Utility.md
> +ACL Tables configuration resieds in CONFIG DB in table *ACL_TABLE*. Tables in *ACL_TABLE* may reference another table *ACL_TABLE_TYPE* that holds the table type configuration or may use one of defaul
Thanks, fixed

2022-05-09 20:16 UTC, vivekreddynv approved these changes

2022-05-11 07:46 UTC, liat-grozovik commented
@bingwang-ms kindly reminder to review.

2022-05-25 15:41 UTC, liat-grozovik approved these changes

2022-05-25 15:41 UTC, merged